# Great reference:  http://www.appveyor.com/docs/appveyor-yml

version: 1.0.{build}
skip_tags: false
configuration: Release
init:
- ps: >-
    $parsedReleaseBuildVersion = $env:APPVEYOR_REPO_TAG_NAME -Match "(\d+.\d+.\d+(.\d+)?)"

    If($env:appveyor_repo_tag -AND $parsedReleaseBuildVersion) 
    {
        $env:BuildVersion = $matches[0]
        $env:IsGithubRelease = $TRUE
    }
    else
    {
        $env:BuildVersion = $env:appveyor_build_version
    }
    
    Write-Host "Build Version: " $env:BuildVersion
    Write-Host "appveyor_build_version Variable: " $env:appveyor_build_version

install:
- ps: >-
    try
    {
        If($env:IsGithubRelease)
        {
            echo (Get-ChildItem -Filter .git -Recurse -Force)[0].FullName
            $origin = git config --get remote.origin.url

            Write-Host "Origin:  " $origin

            if ($origin -like "https://github.com/*.git")
            {
                Write-Host "Origin matches github pattern"
                $releaseUrl = $origin.TrimStart("https://github.com").TrimEnd(".git")
                $releaseUrl = "https://api.github.com/repos/" + $releaseUrl + "/releases" + $env:APPVEYOR_REPO_TAG_NAME

                Echo "Release url:  " $releaseUrl
                $resp = invoke-webrequest $releaseUrl
                $release = $resp.Content | ConvertFrom-Json

                echo "Release notes:  " $release.Body

                $nuspecPath = (Get-ChildItem -Filter *.nuspec -Recurse )[0].FullName
                echo "getting nuspec from " $nuspecPath
                [xml]$nuspec = Get-Content $nuspecPath

                $nuspec.package.metadata.releaseNotes = $release.Body
                echo $nuspec
                echo "Saving updated nuspec"
                $nuspec.Save( $nuspecPath )
            }
        }
    }
    catch 
    {
        Write-Host $_.Exception.GetType().FullName, $_.Exception.Message
    }
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(BuildVersion)
  assembly_file_version: $(BuildVersion)
  assembly_informational_version: $(BuildVersion)
nuget:
  account_feed: true
  project_feed: true
before_build:
- nuget restore MasterDevs.CoolWhip.Test\MasterDevs.CoolWhip.Test.sln
build:
  project: MasterDevs.CoolWhip.Test\MasterDevs.CoolWhip.Test.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: \MasterDevs.CoolWhip.Test\bin\Release\MasterDevs.CoolWhip.Test.nupkg
  name: MasterDevs.CoolWhip.Test
deploy:
- provider: GitHub
  auth_token:
    secure: 6Kc++hw4gNF7gTXwA6MpETVE8+gaMWqaLplEo3i5nLBrpjRKH/QX+yzVf6y1XEjn
  artifact: 
  prerelease: false
  on:
    branch: master
    IsGithubRelease: true
- provider: NuGet
  api_key:
    secure: q3geF5WGZknlKJ75c8iGmpASiiVIQPKnxZx3AUosPcbwOAPvoIjaeHOB2odWb/YZ
  artifact: 
  on:
    branch: master
    IsGithubRelease: true

