# Great reference:  http://www.appveyor.com/docs/appveyor-yml

version: 1.0.{build}
skip_tags: false
configuration: Release
init:
- ps: >-
    $parsedReleaseBuildVersion = $env:APPVEYOR_REPO_TAG_NAME -Match "(\d+.\d+.\d+(.\d+)?)"
    
    If($env:appveyor_repo_tag -AND $parsedReleaseBuildVersion) 
    {
        $env:BuildVersion = $matches[0]
        $env:IsGithubRelease = $TRUE
    }
    else 
    {
        $env:BuildVersion = $env:appveyor_build_version
        $env:IsGithubRelease = ""
    }
    
    Write-Host "Build Version: " $env:BuildVersion
    
    Write-Host "appveyor_build_version Variable: " $env:appveyor_build_version
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(BuildVersion)
  assembly_file_version: $(BuildVersion)
  assembly_informational_version: $(BuildVersion)
nuget:
  account_feed: true
  project_feed: true
before_build:
- nuget restore MasterDevs.CoolWhip.Test\MasterDevs.CoolWhip.Test.sln
build:
  project: MasterDevs.CoolWhip.Test\MasterDevs.CoolWhip.Test.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: \MasterDevs.CoolWhip.Test\bin\Release\MasterDevs.CoolWhip.Test.nupkg
  name: MasterDevs.CoolWhip.Test
deploy:
- provider: GitHub
  auth_token:
    secure: 6Kc++hw4gNF7gTXwA6MpETVE8+gaMWqaLplEo3i5nLBrpjRKH/QX+yzVf6y1XEjn
  artifact: 
  prerelease: false
  on:
    branch: master
    IsGithubRelease: true
- provider: NuGet
  api_key:
    secure: q3geF5WGZknlKJ75c8iGmpASiiVIQPKnxZx3AUosPcbwOAPvoIjaeHOB2odWb/YZ
  artifact: 
  on:
    branch: master
    IsGithubRelease: true
